# Generated by Django 3.2.4 on 2021-07-01 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='isDelievered',
            new_name='isDelivered',
        ),
    ]
