# Generated by Django 3.2.4 on 2021-07-15 05:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='createdAt',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 7, 15, 5, 54, 24, 381241, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
